### ISSUE TITLE
game crashes when trying to buy a drink

### ISSUE THREAD

**Issue by MarxMustermann** [akulakov/little_adventure2#6]
When trying to buy a drink on stage for the game crashed. It works when pressing 'y', but pressing shift to type 'Y' crashes the game 

python3 adv.py 
Traceback (most recent call last):
  File "adv.py", line 3728, in <module>
    main(load_game)
  File "adv.py", line 3197, in main
    rv = handle_ui(B, player)
  File "adv.py", line 3378, in handle_ui
    player.action()
  File "adv.py", line 1941, in action
    BuyADrinkAnthony(B).go()
  File "adv.py", line 2814, in go
    y = pl.talk(ID.anthony, 'Would you like to buy a drink for two kashes?', yesno=1)
  File "adv.py", line 1548, in talk
    return k in 'Yy'
TypeError: 'in <string>' requires string as left operand, not int

**Comment by akulakov** [comment]
Fixed, thanks for the report!
