### ISSUE TITLE
issue running on Windows

### ISSUE THREAD

**Issue by akulakov** [akulakov/little_adventure2#8]
It seems like on windows, unicode chars don't get loaded properly from the map files, so you would get an error like this trying to start the game:

Traceback (most recent call last):
  File ".\adv.py", line 3653, in <module>
    main(load_game)
  File ".\adv.py", line 2922, in main
    player = b1.board_1()
  File ".\adv.py", line 603, in board_1
    containers[3].add1(ID.key1)
IndexError: list index out of range

The error is due to containers (cupboards) not being loaded from the map file, so when a key object is added to the cupboard, there is no cupboard on that level and hence the error.

**Comment by akulakov** [comment]
It's been reported that on windows it does work with Ubuntu 18 WSL + Python3.7, so if you want to play around with it on Windows, this might be the best bet..
